package com.ks.supersync.model.ugyvitel.order;


import javax.xml.bind.annotation.XmlElement;

import com.ks.supersync.model.ugyvitel.order.detail.Details;

public class UgyvitelOrder {

    @XmlElement(name = "WebshopId")
    public String webshopId;
    @XmlElement(name = "ExternalId")
    public String externalId;
    @XmlElement(name = "Currency")
    public String currency;
    @XmlElement(name = "CurrencyRate")
    public String currencyRate;
    @XmlElement(name = "CustomerWebshopId")
    public String customerWebshopId;
    @XmlElement(name = "CustomerCode")
    public String customerCode;
    @XmlElement(name = "Phone")
    public String Phone;
    @XmlElement(name = "Email")
    public String Email;
    @XmlElement(name = "CustomerName")
    public String customerName;
    @XmlElement(name = "CustomerContact")
    public String customerContact;
    @XmlElement(name = "InvoicingZip")
    public String invoicingZip;
    @XmlElement(name = "InvoicingCity")
    public String invoicingCity;
    @XmlElement(name = "InvoicingStreet")
    public String invoicingStreet;
    @XmlElement(name = "InvoicingStaircase")
    public String invoicingStaircase;
    @XmlElement(name = "InvoicingDoor")
    public String invoicingDoor;
    @XmlElement(name = "InvoicingFloor")
    public String invoicingFloor;
    @XmlElement(name = "InvoicingBuilding")
    public String invoicingBuilding;
    @XmlElement(name = "InvoicingNumber")
    public String invoicingNumber;
    @XmlElement(name = "InvoicingPublicDomain")
    public String invoicingPublicDomain;
    @XmlElement(name = "InvoicingCountry")
    public String invoicingCountry;
    @XmlElement(name = "InvoicingCountryState")
    public String invoicingCountryState;
    @XmlElement(name = "DeliveryName")
    public String deliveryName;
    @XmlElement(name = "DeliveryZip")
    public String deliveryZip;
    @XmlElement(name = "DeliveryCity")
    public String deliveryCity;
    @XmlElement(name = "DeliveryStreet")
    public String deliveryStreet;
    @XmlElement(name = "DeliveryStaircase")
    public String deliveryStaircase;
    @XmlElement(name = "DeliveryDoor")
    public String deliveryDoor;
    @XmlElement(name = "DeliveryFloor")
    public String deliveryFloor;
    @XmlElement(name = "DeliveryBuilding")
    public String deliveryBuilding;
    @XmlElement(name = "DeliveryNumber")
    public String deliveryNumber;
    @XmlElement(name = "DeliveryPublicDomain")
    public String deliveryPublicDomain;
    @XmlElement(name = "DeliveryCountry")
    public String deliveryCountry;
    @XmlElement(name = "DeliveryCountryState")
    public String deliveryCountryState;
    @XmlElement(name = "OrderAddressZip")
    public String orderAddressZip;
    @XmlElement(name = "OrderAddressCity")
    public String orderAddressCity;
    @XmlElement(name = "OrderAddressStreet")
    public String orderAddressStreet;
    @XmlElement(name = "OrderAddressNumber")
    public String orderAddressNumber;
    @XmlElement(name = "OrderAddressPublicDomain")
    public String orderAddressPublicDomain;
    @XmlElement(name = "OrderAddressBuilding")
    public String orderAddressBuilding;
    @XmlElement(name = "OrderAddressStaircase")
    public String orderAddressStaircase;
    @XmlElement(name = "OrderAddressFloor")
    public String orderAddressFloor;
    @XmlElement(name = "OrderAddressDoor")
    public String orderAddressDoor;
    @XmlElement(name = "OrderAddressCountry")
    public String orderAddressCountry;
    @XmlElement(name = "DeliveryAddressZip")
    public String deliveryAddressZip;
    @XmlElement(name = "DeliveryAddressCity")
    public String deliveryAddressCity;
    @XmlElement(name = "DeliveryAddressStreet")
    public String deliveryAddressStreet;
    @XmlElement(name = "DeliveryAddressNumber")
    public String deliveryAddressNumber;
    @XmlElement(name = "DeliveryAddressPublicDomain")
    public String deliveryAddressPublicDomain;
    @XmlElement(name = "DeliveryAddressBuilding")
    public String deliveryAddressBuilding;
    @XmlElement(name = "DeliveryAddressStaircase")
    public String deliveryAddressStaircase;
    @XmlElement(name = "DeliveryAddressFloor")
    public String deliveryAddressFloor;
    @XmlElement(name = "DeliveryAddressDoor")
    public String deliveryAddressDoor;
    @XmlElement(name = "DeliveryAddressCountry")
    public String deliveryAddressCountry;
    @XmlElement(name = "TaxNumber")
    public String taxNumber;
    @XmlElement(name = "SequencePrefix")
    public String sequencePrefix;
    @XmlElement(name = "paymentDelayDays")
    public String paymentDelayDays;
    @XmlElement(name = "Paymentmethod")
    public String paymentmethod;
    @XmlElement(name = "DeliveryDate")
    public String deliveryDate;
    @XmlElement(name = "OrderDate")
    public String orderDate;
    @XmlElement(name = "OrderedDate")
    public String orderedDate;
    @XmlElement(name = "NetValue")
    public String netValue;
    @XmlElement(name = "VatValue")
    public String vatValue;
    @XmlElement(name = "GrossValue")
    public String grossValue;
    @XmlElement(name = "TransportMode")
    public String transportMode;
    @XmlElement(name = "TopComment")
    public String topComment;
    @XmlElement(name = "BottomComment")
    public String bottomComment;
    @XmlElement(name = "Details")
    public Details details;
    
}